Repository mobi-projects/chaeg-check, pull requests merged in 2024-05, with the labels that each got.

#26 PR : 페이지 라우팅 등록
  src/constants/index.ts
  src/constants/pages-path.ts
  src/libs/react-router-dom/router.tsx
  src/main.tsx
  src/pages/index.ts
  src/pages/not-found/index.tsx
Labels: chore

#28 PR : tailwind-css 적용 경로 오타 수정
  src/main.tsx
  tailwind.config.js
Labels: /error

#29 PR : 공용컴포넌트 dropdonw 생성
  src/components/dropdown/dropdown.func.ts
  src/components/dropdown/dropdown.hooks.ts
  src/components/dropdown/dropdown.types.ts
  src/components/dropdown/index.tsx
  src/constants/url-keys.ts
Labels: /feat, !P1

#30 feat : dialog 최소 기능 구현
  src/components/dialog/dialog.context.tsx
  src/components/dialog/dialog.hook.ts
  src/components/dialog/dialog.type.ts
  src/components/dialog/index.tsx
  src/components/index.ts
  src/main.tsx
Labels: /feat

#31 PR : 로그인&회원가입 hook form적용완료
  src/pages/sign-in/index.tsx
  src/pages/sign-up/index.tsx
Labels: /feat, !P0

#33 PR : 로딩 중 스켈레톤 ui 를 보여주는 이미지 컴포넌트 작성
  src/components/deferable-img/deferable-img.hook.ts
  src/components/deferable-img/deferable-img.style.ts
  src/components/deferable-img/deferable-img.type.ts
  src/components/deferable-img/index.tsx
  src/components/index.ts
Labels: /publish

#34 PR : pagination 기능 & 배치 작업완료했습니다.
  .gitignore
  src/components/button/index.tsx
  src/components/pagination/index.tsx
  src/components/pagination/pagination.hook.ts
  src/components/pagination/pagination.type.ts
  src/constants/url-keys.ts
Labels: /feat, !P1

#35 PR : axiosInstance생성 & 로그인기능 구현했습니다.
  src/constants/auth-key.ts
  src/libs/axios/instance.ts
  src/pages/sign-in/index.tsx
  src/pages/sign-in/sign-in.func.ts
Labels: /feat, ~Late-1

#36 PR : refresh토큰 재발급로직 & 로그아웃기능 구현
  src/constants/auth-key.ts
  src/constants/server-endpoint.ts
  src/libs/axios/instance.ts
  src/pages/home/index.tsx
  src/pages/sign-in/index.tsx
  src/pages/sign-in/sign-in.func.ts
Labels: /feat, ~Late-1

#37 PR : 도서 목록 불러오기
  src/libs/axios/instance.ts
  src/pages/home/home.constant.ts
  src/pages/home/home.func.ts
  src/pages/home/home.hook.ts
  src/pages/home/home.type.ts
  src/pages/home/index.tsx
  vite.config.ts
Labels: /feat

#42 PR : access token 유무 기준, 페이지 접근제어
  src/components/dialog/dialog.hook.ts
  src/components/dialog/dialog.type.ts
  src/constants/index.ts
  src/libs/react-router-dom/auth-route.tsx
  src/libs/react-router-dom/router.tsx
Labels: /feat

#50 PR : shadcn UI 컴포넌트 코드 추가
  components.json
  package-lock.json
  package.json
  src/components/ui/alert-dialog.tsx
  src/components/ui/alert.tsx
  src/components/ui/aspect-ratio.tsx
  src/components/ui/avatar.tsx
  src/components/ui/badge.tsx
  src/components/ui/breadcrumb.tsx
  src/components/ui/button.tsx
  src/components/ui/checkbox.tsx
  src/components/ui/dialog.tsx
  src/components/ui/form.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/components/ui/menubar.tsx
  src/components/ui/navigation-menu.tsx
  src/components/ui/pagination.tsx
  src/components/ui/popover.tsx
  src/components/ui/progress.tsx
  src/components/ui/radio-group.tsx
  src/components/ui/resizable.tsx
  src/components/ui/scroll-area.tsx
  src/components/ui/select.tsx
  src/components/ui/skeleton.tsx
  src/components/ui/sonner.tsx
  src/components/ui/switch.tsx
  src/components/ui/table.tsx
  src/components/ui/tabs.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toast.tsx
  src/components/ui/toaster.tsx
  src/components/ui/toggle.tsx
  src/components/ui/tooltip.tsx
  src/components/ui/use-toast.ts
  src/libs/tailwind-css/global.css
  src/libs/tailwind-css/tailwind-utils.ts
  tailwind.config.js
Labels: /depend

#51 PR : profileImage등록 기능구현
  src/constants/server-endpoint.ts
  src/pages/my/index.tsx
  src/pages/my/my.func.ts
  src/pages/my/my.hook.ts
  src/pages/my/my.modal.tsx
  src/pages/my/my.type.ts
Labels: /feat, ~Late-1

#58 PR: 공용컴포넌트 header생성
  src/components/header/header.constant.ts
  src/components/header/index.tsx
  src/libs/react-router-dom/auth-route.tsx
  src/libs/react-router-dom/router.tsx
  src/pages/home/index.tsx
  src/pages/my/index.tsx
Labels: /publish, !P1

#60 PR : 도서상세정보 호출 구조 변경
  src/constants/server-endpoint.ts
  src/pages/detail/detail.constant.ts
  src/pages/detail/detail.func.ts
  src/pages/detail/detail.hook.ts
  src/pages/detail/detail.type.ts
  src/pages/detail/index.tsx
Labels: /feat

#63 PR : 특정 도서에 대한 리뷰 등록 기능 구현
  src/pages/detail/detail.func.ts
  src/pages/detail/detail.hook.ts
  src/pages/detail/detail.type.ts
  src/pages/detail/index.tsx
Labels: /feat, !P0

#67 PR : 로그인/회원가입/로그아웃 관련 api 호출함수 리펙토링
  src/components/header/index.tsx
  src/funcs/index.ts
  src/funcs/manage-storage/index.ts
  src/funcs/manage-storage/manage-storage.type.ts
  src/funcs/string-util/index.ts
  src/funcs/string-util/string-util.type.ts
  src/funcs/type-guard/index.ts
  src/pages/sign/sign.func.ts
  src/pages/sign/sign.type.ts
  src/types/user-data.type.ts
Labels: /refactor

#70 PR : 사용자 정보, 전역상태로 관리
  src/constants/index.ts
  src/constants/query-key.ts
  src/constants/server-endpoint.ts
  src/hooks/index.ts
  src/hooks/useUser/index.ts
  src/hooks/useUser/useUser.func.ts
  src/types/convert-axios-res-ft.ts
  src/types/index.ts
Labels: /feat

#72 PR : detail페이지 퍼블리싱 완료했습니다.
  src/pages/detail/components/detail.content.tsx
  src/pages/detail/components/detail.review.tsx
  src/pages/detail/components/detail.title.tsx
  src/pages/detail/components/index.ts
  src/pages/detail/index.tsx
Labels: /publish, !P0

#73 PR : signin mutation
  src/constants/query-key.ts
  src/pages/sign/components/sign-in.form.tsx
  src/pages/sign/sign.func.ts
  src/pages/sign/sign.hooks.ts
  src/pages/sign/sign.type.ts
  src/types/index.ts
  src/types/user.type.ts
Labels: /feat, /refactor

#76 PR : Sign 페이지 반응형적용해서 refactor했습니다.
  src/pages/sign/components/sign-up.header.tsx
  src/pages/sign/index.tsx
  tailwind.config.js
Labels: /refactor, !P0

#75 PR : 로그아웃 관련 리펙토링
  src/components/header/index.tsx
  src/constants/query-key.ts
  src/hooks/index.ts
  src/hooks/use-sign-out/index.tsx
  src/hooks/use-sign-out/use-sign-out.func.ts
  src/pages/sign/sign.func.ts
Labels: /feat

#78 PR : main페이지 반응형 적용했습니다.
  src/components/pagination/index.tsx
  src/pages/home/components/home.card.tsx
  src/pages/home/index.tsx
Labels: /refactor, !P0

#80 PR : detail페이지 반응형 적용했습니다.
  src/pages/detail/components/detail.content.tsx
  src/pages/detail/components/detail.review.tsx
  src/pages/detail/components/detail.title.tsx
  src/pages/detail/index.tsx
Labels: /refactor, !P0

#81 PR : sign-in validate checking
  src/libs/yup/index.ts
  src/libs/yup/schema.ts
  src/pages/sign/components/error-msg.tsx
  src/pages/sign/components/index.ts
  src/pages/sign/components/sign-in.form.tsx
  src/pages/sign/sign.hooks.ts
  src/pages/sign/sign.type.ts
  src/pages/sign/sign.yup-schema.ts
Labels: /feat

#87 PR : dialog 디자인 작업
  src/components/dialog/dialog.cva.ts
  src/components/dialog/index.tsx
Labels: /publish

#94 PR : 메인페이지, 디테일페이지 반응형 수정사항 반영했습니다.
  src/pages/detail/components/detail.content.tsx
  src/pages/home/components/home.card.tsx
Labels: /refactor, !P0

#96 PR : hotfix 로그인 로직 오타 수정했습니다.
  src/pages/sign/components/sign-in.form.tsx
Labels: !P0, /hotfix

#97 PR : detail페이지 댓글목록패칭 완료했습니다.
  src/pages/detail/components/detail.review-list.tsx
  src/pages/detail/components/index.ts
  src/pages/detail/detail.func.ts
  src/pages/detail/index.tsx
Labels: /refactor, !P0

#91 PR : 회원가입 성공 후, dialog 출력과 페이지 전환이 동시진행 이슈 발견
  src/pages/sign/sign.hooks.ts
Labels: /error

#98 PR : 책 가격관련 함수 생성했습니다.
  src/funcs/calculate/calculate.type.ts
  src/funcs/calculate/index.ts
  src/pages/detail/components/detail.content.tsx
  src/pages/detail/detail.func.ts
  src/pages/detail/detail.type.ts
  src/pages/home/components/home.card.tsx
Labels: /refactor, !P0

#101 PR : 책 설명정보 없을때 보여질 text추가했습니다.
  src/pages/home/components/home.card.tsx
Labels: /refactor

#110 PR : my-page 반응형 , 파일관리 refactor했습니다.
  src/components/dialog/dialog.cva.ts
  src/components/dialog/index.tsx
  src/pages/my/components/index.ts
  src/pages/my/components/my.header.tsx
  src/pages/my/components/my.info.tsx
  src/pages/my/components/my.modal-mutate-nick-name.tsx
  src/pages/my/components/my.profile-image.tsx
  src/pages/my/index.tsx
  src/pages/my/my.func.ts
  src/pages/my/my.hook.ts
  src/pages/my/my.modal.tsx
Labels: /refactor

#119 PR : 헤더에 logo이미지 추가 & 클릭시 home으로 이동기능 추가했습니다.
  src/components/header/header.constant.ts
  src/components/header/header.type.ts
  src/components/header/index.tsx
  tailwind.config.js
Labels: /publish, !P1

#123 PR : sign페이지에서 재사용되는 컴포넌트 모듈화를 통해 관심사분리했습니다.
  src/funcs/string-util/string-util.type.ts
  src/funcs/type-guard/index.ts
  src/pages/sign/components/error-msg.tsx
  src/pages/sign/components/index.ts
  src/pages/sign/components/labeled-input.tsx
  src/pages/sign/components/sign-in.form.tsx
  src/pages/sign/components/sign-up.form.tsx
  src/pages/sign/sign.type.ts
Labels: /refactor, !P1

#124 PR : ui수정 요구사항반영해서 sign페이지 refactor
  src/pages/sign/components/sign-in.form.tsx
  src/pages/sign/components/sign-in.header.tsx
  src/pages/sign/components/sign-up.form.tsx
  src/pages/sign/components/sign-up.header.tsx
  src/pages/sign/index.tsx
Labels: /refactor

#127 PR : 잘못된 email, pw 로 접근해도, access-token 획득 issue
  src/libs/axios/base-instance/base-instance.constants.ts
  src/libs/axios/base-instance/base-instance.func.ts
  src/libs/axios/base-instance/base-instance.type.ts
Labels: /error, /hotfix

#132 PR : pagination관련 수정요청사항 반영해서 수정완료
  src/components/dropdown/dropdown.func.ts
  src/components/dropdown/dropdown.hooks.ts
  src/components/dropdown/dropdown.types.ts
  src/components/dropdown/index.tsx
  src/components/index.ts
  src/components/pagination/index.tsx
  src/components/pagination/pagination.func.ts
  src/components/pagination/pagination.hook.ts
  src/components/pagination/pagination.type.ts
  src/constants/index.ts
  src/constants/pagination.ts
  src/constants/url-keys.ts
  src/libs/axios/aladin-instance/index.ts
  src/pages/home/home.constant.ts
  src/pages/home/home.suspense.tsx
  src/pages/home/index.tsx
Labels: /refactor

#130 PR : sign-in 로직, 함수 호출 순서 개선
  src/pages/sign/sign.func.ts
  src/pages/sign/sign.hooks.ts
  src/pages/sign/sign.type.ts
Labels: /refactor
